services:
  db:
    image: postgres:16-alpine
    container_name: eva02_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: desarrollo_software_1
      POSTGRES_USER: root
      POSTGRES_PASSWORD: desarrollo_software_1
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root -d desarrollo_software_1']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
